#!/usr/bin/env escript
%% -*- erlang -*-
%%! -name volunteer_mgr@localhost.localdomain -pa ./_build/default/lib/volunteer_mgr/ebin -mnesia debug verbose
main([]) ->
    main([node()]);
main([Dir]) ->
    try
        stopped = mnesia:stop(),
        application:set_env(mnesia, dir, Dir),
		io:format("Creating mnesia schema in: ~p~n", [mnesia:system_info(directory)]),
        handle_create_schema(mnesia:create_schema([node()]))
    catch
        ErrT:Err ->
            io:format(standard_error, "Caught error: ~p:~p~n", [ErrT, Err]),
            usage()
    end;
main(_) ->
    usage().

usage() ->
    io:format("usage: create_schema [directory]\n"),
    halt(1).

handle_create_schema(ok) ->
    ok = mnesia:start(),
    handle_init_tables(volmgr_db:init_tables(disc_copies));
handle_create_schema(Err) ->
    io:format(standard_error, "Create schema unexpected result: ~p~n", [Err]).

handle_init_tables(ok) ->
    ok;
handle_init_tables(Err) ->
    io:format(standard_error, "Init tables unexpected result: ~p~n", [Err]).
